/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["f-lineage should match snpashot"] = `<g>
  <g
    class="links"
    data-page="1"
  >
    <path
      class="forward-link lineage-element link"
      d="M216,42L234,42L246,42L304,42L316,42"
      fill="none"
      id="noede1->node2"
      stroke="var(--color-border-default)"
      stroke-dasharray="0"
      stroke-width="2"
    >
    </path>
    <path
      class="forward-link lineage-element link"
      d="M516,42L534,42L546,42L604,42L616,42"
      fill="none"
      id="node2->node5"
      stroke="var(--color-border-default)"
      stroke-dasharray="0"
      stroke-width="2"
    >
    </path>
    <path
      class="forward-link lineage-element link"
      d="M816,42L834,42L846,42L904,42L916,42"
      fill="none"
      id="node5->node3"
      stroke="var(--color-border-default)"
      stroke-dasharray="0"
      stroke-width="2"
    >
    </path>
    <path
      class="forward-link lineage-element link"
      d="M816,42L834,42A12,12,0,0,1,846,54L846,182A12,12,0,0,0,858,194L904,194L916,194"
      fill="none"
      id="node5->node4"
      stroke="var(--color-border-default)"
      stroke-dasharray="0"
      stroke-width="2"
    >
    </path>
    <path
      class="distant-link forward-link lineage-element link"
      d="M216,194L244,194A12,12,0,0,0,256,182L256,194A12,12,0,0,1,268,182L504,182L516,182L534,182A12,12,0,0,0,546,170L546,54A12,12,0,0,1,558,42L604,42L616,42"
      fill="none"
      id="node6->node5"
      stroke="var(--color-border-default)"
      stroke-dasharray="0"
      stroke-width="2"
    >
    </path>
    <path
      class="backward-link lineage-element link"
      d="M216,194L244,194A12,12,0,0,1,256,206L256,258A12,12,0,0,1,244,270L-12,270L-24,270L-52,270A12,12,0,0,1,-64,258L-64,206A12,12,0,0,1,-52,194L4,194L16,194"
      fill="none"
      id="node6->node6"
      stroke="var(--color-border-default)"
      stroke-dasharray="0"
      stroke-width="2"
    >
    </path>
    <circle
      class="lineage-element source-dot"
      cx="216"
      cy="42"
      fill="var(--color-border-default)"
      id="source-dot-noede1->node2"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element source-dot"
      cx="516"
      cy="42"
      fill="var(--color-border-default)"
      id="source-dot-node2->node5"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element source-dot"
      cx="816"
      cy="42"
      fill="var(--color-border-default)"
      id="source-dot-node5->node3"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element source-dot"
      cx="816"
      cy="42"
      fill="var(--color-border-default)"
      id="source-dot-node5->node4"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element source-dot"
      cx="216"
      cy="194"
      fill="var(--color-border-default)"
      id="source-dot-node6->node5"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element source-dot"
      cx="216"
      cy="194"
      fill="var(--color-border-default)"
      id="source-dot-node6->node6"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element target-dot"
      cx="316"
      cy="42"
      fill="var(--color-border-default)"
      id="noede1->node2~target-dot"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element target-dot"
      cx="616"
      cy="42"
      fill="var(--color-border-default)"
      id="node2->node5~target-dot"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element target-dot"
      cx="916"
      cy="42"
      fill="var(--color-border-default)"
      id="node5->node3~target-dot"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element target-dot"
      cx="916"
      cy="194"
      fill="var(--color-border-default)"
      id="node5->node4~target-dot"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element target-dot"
      cx="616"
      cy="42"
      fill="var(--color-border-default)"
      id="node6->node5~target-dot"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element target-dot"
      cx="16"
      cy="194"
      fill="var(--color-border-default)"
      id="node6->node6~target-dot"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <text
      class="lineage-element link-arrow"
      dx="-0.8"
      dy="6.5"
      id="noede1->node2~arrow"
      stroke="var(--color-surface-default)"
      stroke-width="1px"
    >
      <textpath
        fill="var(--color-border-default)"
        startoffset="100%"
        text-anchor="end"
        xlink:href="#noede1->node2"
      >
        ▶
      </textpath>
    </text>
    <text
      class="lineage-element link-arrow"
      dx="-0.8"
      dy="6.5"
      id="node2->node5~arrow"
      stroke="var(--color-surface-default)"
      stroke-width="1px"
    >
      <textpath
        fill="var(--color-border-default)"
        startoffset="100%"
        text-anchor="end"
        xlink:href="#node2->node5"
      >
        ▶
      </textpath>
    </text>
    <text
      class="lineage-element link-arrow"
      dx="-0.8"
      dy="6.5"
      id="node5->node3~arrow"
      stroke="var(--color-surface-default)"
      stroke-width="1px"
    >
      <textpath
        fill="var(--color-border-default)"
        startoffset="100%"
        text-anchor="end"
        xlink:href="#node5->node3"
      >
        ▶
      </textpath>
    </text>
    <text
      class="lineage-element link-arrow"
      dx="-0.8"
      dy="6.5"
      id="node5->node4~arrow"
      stroke="var(--color-surface-default)"
      stroke-width="1px"
    >
      <textpath
        fill="var(--color-border-default)"
        startoffset="100%"
        text-anchor="end"
        xlink:href="#node5->node4"
      >
        ▶
      </textpath>
    </text>
    <text
      class="lineage-element link-arrow"
      dx="-0.8"
      dy="6.5"
      id="node6->node5~arrow"
      stroke="var(--color-surface-default)"
      stroke-width="1px"
    >
      <textpath
        fill="var(--color-border-default)"
        startoffset="100%"
        text-anchor="end"
        xlink:href="#node6->node5"
      >
        ▶
      </textpath>
    </text>
    <text
      class="lineage-element link-arrow"
      dx="-0.8"
      dy="6.5"
      id="node6->node6~arrow"
      stroke="var(--color-surface-default)"
      stroke-width="1px"
    >
      <textpath
        fill="var(--color-border-default)"
        startoffset="100%"
        text-anchor="end"
        xlink:href="#node6->node6"
      >
        ▶
      </textpath>
    </text>
  </g>
  <g
    class="nodes"
    data-page="1"
  >
    <g
      class="lineage-element lineage-node"
      id="noede1"
      transform="translate(16,16)"
    >
      <foreignobject
        class="center-node"
        height="52"
        id="noede1-foreign-object"
        width="200"
      >
        <f-div
          align="middle-left"
          gap="small"
          height="100%"
          padding="none medium"
          state="secondary"
          variant="curved"
          width="100%"
        >
          <f-text
            ellipsis=""
            size="large"
            variant="code"
          >
            noede1
          </f-text>
          <f-icon-button
            class="children-toggle"
            icon="i-chevron-down"
            size="x-small"
            state="inherit"
            type="transparent"
          >
          </f-icon-button>
        </f-div>
      </foreignobject>
    </g>
    <g
      class="lineage-element lineage-node"
      id="node2"
      transform="translate(316,16)"
    >
      <foreignobject
        height="52"
        id="node2-foreign-object"
        width="200"
      >
        <f-div
          align="middle-left"
          border="small solid default bottom"
          gap="small"
          height="100%"
          padding="none medium"
          state="secondary"
          variant="curved"
          width="100%"
        >
          <f-text
            ellipsis=""
            size="large"
            variant="code"
          >
            node2
          </f-text>
          <f-icon-button
            class="children-toggle"
            icon="i-chevron-up"
            size="x-small"
            state="inherit"
            type="transparent"
          >
          </f-icon-button>
        </f-div>
      </foreignobject>
    </g>
    <g
      class="lineage-element lineage-node"
      id="node5"
      transform="translate(616,16)"
    >
      <foreignobject
        height="52"
        id="node5-foreign-object"
        width="200"
      >
        <f-div
          align="middle-left"
          border="small solid default bottom"
          gap="small"
          height="100%"
          padding="none medium"
          state="secondary"
          variant="curved"
          width="100%"
        >
          <f-text
            ellipsis=""
            size="large"
            variant="code"
          >
            node5
          </f-text>
          <f-icon-button
            class="children-toggle"
            icon="i-chevron-up"
            size="x-small"
            state="inherit"
            type="transparent"
          >
          </f-icon-button>
        </f-div>
      </foreignobject>
    </g>
    <g
      class="lineage-element lineage-node"
      id="node3"
      transform="translate(916,16)"
    >
      <foreignobject
        height="52"
        id="node3-foreign-object"
        width="200"
      >
        <f-div
          align="middle-left"
          gap="small"
          height="100%"
          padding="none medium"
          state="secondary"
          variant="curved"
          width="100%"
        >
          <f-text
            ellipsis=""
            size="large"
            variant="code"
          >
            node3
          </f-text>
        </f-div>
      </foreignobject>
    </g>
    <g
      class="lineage-element lineage-node"
      id="node4"
      transform="translate(916,168)"
    >
      <foreignobject
        height="52"
        id="node4-foreign-object"
        width="200"
      >
        <f-div
          align="middle-left"
          border="small solid default bottom"
          gap="small"
          height="100%"
          padding="none medium"
          state="secondary"
          variant="curved"
          width="100%"
        >
          <f-text
            ellipsis=""
            size="large"
            variant="code"
          >
            node4
          </f-text>
          <f-icon-button
            class="children-toggle"
            icon="i-chevron-up"
            size="x-small"
            state="inherit"
            type="transparent"
          >
          </f-icon-button>
        </f-div>
      </foreignobject>
    </g>
    <g
      class="lineage-element lineage-node"
      id="node6"
      transform="translate(16,168)"
    >
      <foreignobject
        height="52"
        id="node6-foreign-object"
        width="200"
      >
        <f-div
          align="middle-left"
          gap="small"
          height="100%"
          padding="none medium"
          state="secondary"
          variant="curved"
          width="100%"
        >
          <f-text
            ellipsis=""
            size="large"
            variant="code"
          >
            node6
          </f-text>
        </f-div>
      </foreignobject>
    </g>
  </g>
  <g
    class="scrollable-children"
    data-page="1"
  >
    <g
      class="children-container"
      data-max="8"
      data-offset="0"
      data-parent-id="node2"
      id="scrollable-node2"
    >
      <g
        class="child-node child-node-node2 lineage-element lineage-node"
        data-page="1"
        data-parent-id="node2"
        id="node2child1"
        transform="translate(316,68)"
      >
        <foreignobject
          height="32"
          id="node2child1-foreign-object"
          width="200"
        >
          <f-div
            align="middle-left"
            border="small solid default bottom"
            gap="small"
            height="100%"
            padding="none medium"
            state="secondary"
            variant="curved"
            width="100%"
          >
            <f-text
              ellipsis=""
              size="large"
              variant="code"
            >
              node2child1
            </f-text>
          </f-div>
        </foreignobject>
      </g>
      <g
        class="child-node child-node-node2 lineage-element lineage-node"
        data-page="1"
        data-parent-id="node2"
        id="node2child2"
        transform="translate(316,100)"
      >
        <foreignobject
          height="32"
          id="node2child2-foreign-object"
          width="200"
        >
          <f-div
            align="middle-left"
            border="small solid default bottom"
            gap="small"
            height="100%"
            padding="none medium"
            state="secondary"
            variant="curved"
            width="100%"
          >
            <f-text
              ellipsis=""
              size="large"
              variant="code"
            >
              node2child2
            </f-text>
          </f-div>
        </foreignobject>
      </g>
    </g>
    <g
      class="children-container"
      data-max="8"
      data-offset="0"
      data-parent-id="node5"
      id="scrollable-node5"
    >
      <g
        class="child-node child-node-node5 lineage-element lineage-node"
        data-page="1"
        data-parent-id="node5"
        id="node5child1"
        transform="translate(616,68)"
      >
        <foreignobject
          height="32"
          id="node5child1-foreign-object"
          width="200"
        >
          <f-div
            align="middle-left"
            border="small solid default bottom"
            gap="small"
            height="100%"
            padding="none medium"
            state="secondary"
            variant="curved"
            width="100%"
          >
            <f-text
              ellipsis=""
              size="large"
              variant="code"
            >
              node5child1
            </f-text>
          </f-div>
        </foreignobject>
      </g>
      <g
        class="child-node child-node-node5 lineage-element lineage-node"
        data-page="1"
        data-parent-id="node5"
        id="node5child3"
        transform="translate(616,100)"
      >
        <foreignobject
          height="32"
          id="node5child3-foreign-object"
          width="200"
        >
          <f-div
            align="middle-left"
            border="small solid default bottom"
            gap="small"
            height="100%"
            padding="none medium"
            state="secondary"
            variant="curved"
            width="100%"
          >
            <f-text
              ellipsis=""
              size="large"
              variant="code"
            >
              node5child3
            </f-text>
          </f-div>
        </foreignobject>
      </g>
      <g
        class="child-node child-node-node5 lineage-element lineage-node"
        data-page="1"
        data-parent-id="node5"
        id="node5child2"
        transform="translate(616,132)"
      >
        <foreignobject
          height="32"
          id="node5child2-foreign-object"
          width="200"
        >
          <f-div
            align="middle-left"
            border="small solid default bottom"
            gap="small"
            height="100%"
            padding="none medium"
            state="secondary"
            variant="curved"
            width="100%"
          >
            <f-text
              ellipsis=""
              size="large"
              variant="code"
            >
              node5child2
            </f-text>
          </f-div>
        </foreignobject>
      </g>
    </g>
    <g
      class="children-container"
      data-max="8"
      data-offset="0"
      data-parent-id="node4"
      id="scrollable-node4"
    >
      <g
        class="child-node child-node-node4 lineage-element lineage-node"
        data-page="1"
        data-parent-id="node4"
        id="node4child1"
        transform="translate(916,220)"
      >
        <foreignobject
          height="32"
          id="node4child1-foreign-object"
          width="200"
        >
          <f-div
            align="middle-left"
            border="small solid default bottom"
            gap="small"
            height="100%"
            padding="none medium"
            state="secondary"
            variant="curved"
            width="100%"
          >
            <f-text
              ellipsis=""
              size="large"
              variant="code"
            >
              node4child1
            </f-text>
          </f-div>
        </foreignobject>
      </g>
      <g
        class="child-node child-node-node4 lineage-element lineage-node"
        data-page="1"
        data-parent-id="node4"
        id="node4child2"
        transform="translate(916,252)"
      >
        <foreignobject
          height="32"
          id="node4child2-foreign-object"
          width="200"
        >
          <f-div
            align="middle-left"
            border="small solid default bottom"
            gap="small"
            height="100%"
            padding="none medium"
            state="secondary"
            variant="curved"
            width="100%"
          >
            <f-text
              ellipsis=""
              size="large"
              variant="code"
            >
              node4child2
            </f-text>
          </f-div>
        </foreignobject>
      </g>
    </g>
  </g>
  <g
    class="links"
    data-page="1"
  >
  </g>
  <g
    class="links"
    data-page="1"
  >
    <path
      class="child-link distant-link forward-link lineage-element link"
      d="M216,42L234,42A12,12,0,0,1,246,54L246,170A12,12,0,0,0,258,182L504,182L516,182L534,182A12,12,0,0,0,546,170L546,160A12,12,0,0,1,558,148L604,148L616,148"
      data-parent-id="noede1->node5child2"
      fill="none"
      id="node1child1->node5child2"
      stroke="var(--color-border-default)"
      stroke-dasharray="8 4"
      stroke-width="2"
    >
    </path>
    <circle
      class="lineage-element source-dot"
      cx="216"
      cy="42"
      data-parent-id="noede1->node5child2"
      fill="var(--color-border-default)"
      id="source-dot-node1child1->node5child2"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element target-dot"
      cx="616"
      cy="148"
      data-parent-id="noede1->node5child2"
      fill="var(--color-border-default)"
      id="node1child1->node5child2~target-dot"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <text
      class="child-link lineage-element link-arrow"
      data-parent-id="noede1->node5child2"
      dx="-0.8"
      dy="6.5"
      id="node1child1->node5child2~arrow"
      stroke="var(--color-surface-default)"
      stroke-width="1px"
    >
      <textpath
        fill="var(--color-border-default)"
        startoffset="100%"
        text-anchor="end"
        xlink:href="#node1child1->node5child2"
      >
        ▶
      </textpath>
    </text>
  </g>
  <g
    class="links"
    data-page="1"
  >
    <path
      class="backward-link child-link lineage-element link"
      d="M1116,236L1134,236A12,12,0,0,1,1146,248L1146,322A12,12,0,0,1,1134,334L898,334L886,334L868,334A12,12,0,0,1,856,322L856,226A12,12,0,0,0,844,214L598,214L586,214L568,214A12,12,0,0,1,556,202L556,160A12,12,0,0,1,568,148L604,148L616,148"
      fill="none"
      id="node4child1->node5child2"
      stroke="var(--color-border-default)"
      stroke-dasharray="0"
      stroke-width="2"
    >
    </path>
    <path
      class="backward-link child-link lineage-element link"
      d="M1116,236L1134,236A12,12,0,0,1,1146,248L1146,322A12,12,0,0,1,1134,334L898,334L886,334L868,334A12,12,0,0,1,856,322L856,226A12,12,0,0,0,844,214L598,214L586,214L568,214A12,12,0,0,1,556,202L556,96A12,12,0,0,1,568,84L604,84L616,84"
      fill="none"
      id="node4child1->node5child1"
      stroke="var(--color-border-default)"
      stroke-dasharray="0"
      stroke-width="2"
    >
    </path>
    <path
      class="child-link distant-link forward-link lineage-element link"
      d="M216,42L234,42A12,12,0,0,1,246,54L246,170A12,12,0,0,0,258,182L504,182L516,182L534,182A12,12,0,0,1,546,194L546,202A12,12,0,0,0,558,214L804,214L816,214L844,214A12,12,0,0,1,856,226L856,256A12,12,0,0,0,868,268L904,268L916,268"
      data-parent-id="noede1->node4child2"
      fill="none"
      id="node1child1->node4child2"
      stroke="var(--color-border-default)"
      stroke-dasharray="8 4"
      stroke-width="2"
    >
    </path>
    <circle
      class="lineage-element source-dot"
      cx="1116"
      cy="236"
      fill="var(--color-border-default)"
      id="source-dot-node4child1->node5child2"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element source-dot"
      cx="1116"
      cy="236"
      fill="var(--color-border-default)"
      id="source-dot-node4child1->node5child1"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element source-dot"
      cx="216"
      cy="42"
      data-parent-id="noede1->node4child2"
      fill="var(--color-border-default)"
      id="source-dot-node1child1->node4child2"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element target-dot"
      cx="616"
      cy="148"
      fill="var(--color-border-default)"
      id="node4child1->node5child2~target-dot"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element target-dot"
      cx="616"
      cy="84"
      fill="var(--color-border-default)"
      id="node4child1->node5child1~target-dot"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <circle
      class="lineage-element target-dot"
      cx="916"
      cy="268"
      data-parent-id="noede1->node4child2"
      fill="var(--color-border-default)"
      id="node1child1->node4child2~target-dot"
      r="6"
      stroke="var(--color-surface-default)"
      stroke-width="2px"
    >
    </circle>
    <text
      class="child-link lineage-element link-arrow"
      dx="-0.8"
      dy="6.5"
      id="node4child1->node5child2~arrow"
      stroke="var(--color-surface-default)"
      stroke-width="1px"
    >
      <textpath
        fill="var(--color-border-default)"
        startoffset="100%"
        text-anchor="end"
        xlink:href="#node4child1->node5child2"
      >
        ▶
      </textpath>
    </text>
    <text
      class="child-link lineage-element link-arrow"
      dx="-0.8"
      dy="6.5"
      id="node4child1->node5child1~arrow"
      stroke="var(--color-surface-default)"
      stroke-width="1px"
    >
      <textpath
        fill="var(--color-border-default)"
        startoffset="100%"
        text-anchor="end"
        xlink:href="#node4child1->node5child1"
      >
        ▶
      </textpath>
    </text>
    <text
      class="child-link lineage-element link-arrow"
      data-parent-id="noede1->node4child2"
      dx="-0.8"
      dy="6.5"
      id="node1child1->node4child2~arrow"
      stroke="var(--color-surface-default)"
      stroke-width="1px"
    >
      <textpath
        fill="var(--color-border-default)"
        startoffset="100%"
        text-anchor="end"
        xlink:href="#node1child1->node4child2"
      >
        ▶
      </textpath>
    </text>
  </g>
  <g
    class="lineage-element scrollbars"
    data-page="1"
  >
  </g>
</g>
`;
/* end snapshot f-lineage should match snpashot */
