#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn workspace @cldcvr/flow-core compile && yarn workspace @cldcvr/flow-core test-build && yarn workspace @cldcvr/flow-log compile && yarn workspace @cldcvr/flow-log test-build && yarn workspace @cldcvr/flow-code-editor compile && git add -A
